---

- name: zsh installieren
  package:
    name: zsh
    state: present
  
- name: download ohmyzsh
  get_url:
    url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    dest: /tmp/install_ohmyzsh.sh

- name: install ohmyzsh
  shell: sh /tmp/install_ohmyzsh.sh --unattended

- name: set config
  copy: 
    src: zshrc
    dest: "{{HOME_PATH}}/.zshrc"


